wp-tool.svn.db-define.dir=/SVN_CITS/documents/04_内部設計/02_作成ドキュメント/50_機能設計/80_DB設計書/02_テーブル定義/

wp-tool.cache-dir=./target/cache

wp-tool.db.db-define.cachefile=./target/cache/wp-db.cache

wp-tool.svn.session-items-define.file=/test/模版/副本04_50_45_01_09_【共通仕様】セッション管理項目一覧1.xlsx

wp-tool.svn.base-dir=D:/WORK/128SYIS25142_devora


wp-tool.ai.support.url=https://devora.neusoft.work/backend/api/v1/projects/128SYIS25142/commands/69b892bc6fda971e8977a42b/file/invoke
wp-tool.ai.support.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOiJkZWZhdWx0IiwidWNzX3VzZXJfaWQiOm51bGwsInRlbmFudF9uYW1lIjoi6buY6K6k56ef5oi3IiwicHJpbWFyeV9ncm91cCI6IjY4NDE0Y2Q3ZTRiMDYyYmI1MjVlNmZlOSIsInJvbGVzIjpbImRlZmF1bHQiLCI2ODQxNGNkN2U0YjA2MmJiNTI1ZTZmZTkiXSwiYXZhdGFyIjpudWxsLCJ1dWlkIjoiNjliN2E5MzFlNGIwZGRiOWQzN2RmM2U3IiwiYXV0aG9yaXRpZXMiOlsiR1JPVVBfNjg0MTRjZDdlNGIwNjJiYjUyNWU2ZmU5Il0sImNsaWVudF9pZCI6ImRvYy1waWxvdCIsInN1cGVyX2FkbWluIjpmYWxzZSwidGVuYW50X2FkbWluIjpmYWxzZSwic2NvcGUiOltdLCJuYW1lIjoi5bCP5by554-gIiwiZXhwIjoyMDg5MDY0Njg2LCJqdGkiOiI2Y2ZiNjg2Yi1kZjNjLTQxZTAtYTJlOS1kZjQ1OGVkYTlkNmMiLCJ1c2VybmFtZSI6IjcxM2VhMDNlZWVkODQyODhhM2UxZDk0Mzk5Y2RhMzU4In0.jjYcZsMAou65-xUP2LYF2CFCSc5t5GZbJ1fyBDJ2Sy0

