wp-tool.svn.base-dir=D:\\WORK\\128SYIS25142_devora

wp-tool.svn.db-define.dir=\\SVN_CITS\\documents\\04_内部設計\\02_作成ドキュメント\\50_機能設計\\80_DB設計書\\02_テーブル定義\\

wp-tool.db.db-define.cachefile=./target/cache/wp-db.cache